name: gen_rfm
channels:
  - conda-forge
  - plotly

  - nodefaults

dependencies:
  - python=3.9
  - pip >=21.1
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - pytask>=0.0.14
  - pytask-latex>=0.0.12

  # Misc
  - black
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pdbpp
  - ipykernel
  - jupyterlab
  - pyyaml
  - plotly>=5.5.0
  - plotly-geo
  - pandas
  - statsmodels
  - python-graphviz
  - python-kaleido
  - econml
  - matplotlib
  - scikit-learn

  - pip:
    - -e .  # installs the project
