name: gen_rfm_2
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0.1

  - black=23.1.0
  - conda-lock=1.4.0
  - econml=0.12.0
  - ipykernel=6.21.2
  - jupyterlab=3.6.1
  - matplotlib=3.7.0
  - pandas=1.5.3
  - pdbpp=0.10.3
  - plotly=5.13.1
  - pre-commit=3.1.1
  - pytest=7.2.2
  - pytest-cov=4.0.0
  - pytest-xdist=3.2.0
  - python-graphviz=0.20.1
  - python-kaleido=0.2.1
  - pyyaml=6.0
  - scikit-learn=1.2.1
  - setuptools_scm=7.1.0
  - statsmodels=0.13.5
  - toml=0.10.2
  - tox-conda=0.10.2

  - pip:
    - pytask==0.2.0
    - pytask-latex==0.2.0
    - -e .